# Generated by Django 4.1.2 on 2022-10-22 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_transportprovider_vehicledetail_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='trip.vehicledetail'),
            preserve_default=False,
        ),
    ]
